// <auto-generated />
using System;
using CreatorRizz.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CreatorRizz.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CreatorRizzDbContext))]
    partial class CreatorRizzDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CreatorRizz.Domain.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("checksum");

                    b.Property<string>("LicenseEvidence")
                        .HasColumnType("text")
                        .HasColumnName("license_evidence");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_key");

                    b.Property<string>("RightsStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rights_status");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Checksum")
                        .IsUnique();

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("CreatorRizz.Domain.AssetUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<int?>("InMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("in_milliseconds");

                    b.Property<string>("NarrativePurpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("narrative_purpose");

                    b.Property<int?>("OutMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("out_milliseconds");

                    b.Property<Guid>("ProductionId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_id");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ProductionId");

                    b.ToTable("asset_usages", (string)null);
                });

            modelBuilder.Entity("CreatorRizz.Domain.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("actor");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId", "OccurredAt");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("CreatorRizz.Domain.Production", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<Guid>("TopicCandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_candidate_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TopicCandidateId");

                    b.ToTable("productions", (string)null);
                });

            modelBuilder.Entity("CreatorRizz.Domain.ResearchPack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FactsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("facts_json");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<Guid>("TopicCandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_candidate_id");

                    b.Property<string>("UncertaintyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("uncertainty_json");

                    b.HasKey("Id");

                    b.HasIndex("TopicCandidateId")
                        .IsUnique();

                    b.ToTable("research_packs", (string)null);
                });

            modelBuilder.Entity("CreatorRizz.Domain.ReviewDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("decision");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kind");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("ProductionId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_id");

                    b.Property<string>("ReviewerId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("reviewer_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId");

                    b.ToTable("review_decisions", (string)null);
                });

            modelBuilder.Entity("CreatorRizz.Domain.ScriptVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ClaimMapJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("claim_map_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProductionId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ProductionId", "Version")
                        .IsUnique();

                    b.ToTable("script_versions", (string)null);
                });

            modelBuilder.Entity("CreatorRizz.Domain.SourceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<string>("Excerpt")
                        .HasColumnType("text")
                        .HasColumnName("excerpt");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("publisher");

                    b.Property<int>("ReliabilityScore")
                        .HasColumnType("integer")
                        .HasColumnName("reliability_score");

                    b.Property<Guid>("TopicCandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_candidate_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("TopicCandidateId");

                    b.ToTable("source_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_source_items_reliability_score", "reliability_score BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("CreatorRizz.Domain.TopicCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("canonical_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Creator")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("creator");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<decimal>("ViralScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("viral_score");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalUrl")
                        .IsUnique();

                    b.ToTable("topic_candidates", (string)null);
                });

            modelBuilder.Entity("CreatorRizz.Domain.AssetUsage", b =>
                {
                    b.HasOne("CreatorRizz.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CreatorRizz.Domain.Production", null)
                        .WithMany()
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CreatorRizz.Domain.Production", b =>
                {
                    b.HasOne("CreatorRizz.Domain.TopicCandidate", null)
                        .WithMany()
                        .HasForeignKey("TopicCandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CreatorRizz.Domain.ResearchPack", b =>
                {
                    b.HasOne("CreatorRizz.Domain.TopicCandidate", null)
                        .WithMany()
                        .HasForeignKey("TopicCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CreatorRizz.Domain.ReviewDecision", b =>
                {
                    b.HasOne("CreatorRizz.Domain.Production", null)
                        .WithMany()
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CreatorRizz.Domain.ScriptVersion", b =>
                {
                    b.HasOne("CreatorRizz.Domain.Production", null)
                        .WithMany()
                        .HasForeignKey("ProductionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CreatorRizz.Domain.SourceItem", b =>
                {
                    b.HasOne("CreatorRizz.Domain.TopicCandidate", null)
                        .WithMany()
                        .HasForeignKey("TopicCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
