namespace CreatorRizz.Domain;

/// <summary>
/// Immutable metadata returned by object storage after a file is persisted.
/// The ObjectKey is generated by storage from the content hash, never supplied by the caller.
/// </summary>
public sealed record StoredObject(string ObjectKey, string Checksum, long Length);
